# Begin Project
project:
  type: tutorial-template
  # FYI: the tutorial-template project type is defined in the lmu-osc/tutorial-template extension
# End Project

# Begin Website
repo-url: https://github.com/lmu-osc/FAIR-Data-Management
website:
  title: "FAIR Research Data Management Tutorial"
  page-footer:
    border: false
    center: © 2025 Maike Kleemeyer, Larissa Leiminger, Laura Meier, David Walter. Published by LMU Open Science Center. Licensed under CC BY-SA 4.0.
  repo-url: https://github.com/lmu-osc/FAIR-Data-Management

  navbar:
    right:
      - about.qmd
    left:
      - href: index.qmd
        text: Home
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/lmu-osc/FAIR-Data-Management
          - text: Report a Bug
            href: https://github.com/lmu-osc/FAIR-Data-Management/issues
      - icon: house-heart
        url: https://www.osc.lmu.de/

  sidebar:
    style: "docked"
    contents:
      - text: "Overview"
        href: index.qmd
      - section: "1) Publication"
        href: publication.qmd
        contents:
          - href: publication.qmd#data-availability-statement
            text: "Data Availability Statement"
          - href: publication.qmd#license
            text: "License"
          - href: publication.qmd#persistent-identifier
            text: "Persistent Identifier"
          - href: publication.qmd#repository
            text: "Repository"
      - section: "2) Documentation"
        href: documentation.qmd
        contents:
          - href: documentation.qmd#metadata
            text: "Metadata"
          - href: documentation.qmd#readme-file
            text: "README File"
          - href: documentation.qmd#codebook
            text: "Codebook"
      - section: "3) Organization"
        href: data-organisation.qmd
        contents:
          - href: data-organisation.qmd#general-notes
            text: "General Notes"
          - href: data-organisation.qmd#folder-structure
            text: "Folder Structure"
          - href: data-organisation.qmd#file-and-folder-names
            text: "File and Folder Names"
          - href: data-organisation.qmd#file-formats
            text: "File Formats"
      - section: "4) Data Management Plans"
        href: dmp.qmd
        contents:
          - href: dmp.qmd#general-information
            text: "General Information"
          - href: dmp.qmd#components-of-a-dmp
            text: "Components of a DMP"
          - href: dmp.qmd#example-data-storage-and-security
            text: "Example: Data Storage and Security"
          - href: dmp.qmd#why-is-a-dmp-helpful
            text: "Why is a DMP Helpful?"
          - href: dmp.qmd#dmp-tool-rdmo
            text: "DMP Tool: RDMO"
# End Website

# Begin Includes
include-in-header:
  - file: matomo-analytics.html
include-after-body:
  - file: footer/footer.html
# End Includes

# Begin Format
# use only if needed. the default format for `tutorial-template` projects is tutorial-template-html+tutorial
# we recommend just extending the definition below if you need to make format changes
format:
  tutorial-template-html+tutorial:
    css:
      - footer/footer-style.css
# End Format

# Begin Editor
editor: source
# End Editor

bibliography: references.bib
