---
title: "About"
date: 2025-05-05
citation:
  type: webpage
  title: "FAIR Research Data Management Tutorial"
  container-title: "LMU Open Science Center"
  url: https://lmu-osc.github.io/FAIR-Data-Management/
  doi: "10.5281/zenodo.22249817"
  version: 0.1.0
author:
  - name: Maike Kleemeyer
    orcid: 0000-0002-9388-5535
    email: kleemeyer@mpib-berlin.mpg.de
    affiliation:
      - name: Max Planck Institute for Human Development
        city: Berlin
        url: https://www.mpib-berlin.mpg.de/en 
        
  - name: Larissa Leiminger
    orcid: 0000-0002-6491-3197
    email: leiminger@mpdl.mpg.de
    affiliation:
      - name: Max Planck Digital Library
        city: Munich
        url: https://www.mpdl.mpg.de/en/
  
  - name: Laura Meier
    orcid: 0000-0003-1368-2306
    email: Laura.Meier@ub.uni-muenchen.de
    affiliation:
      - name: University Library of Ludwig-Maximilians-Universität
        city: Munich
        url: https://www.en.ub.uni-muenchen.de
        
  - name: David Walter
    orcid: 0000-0001-6807-5007
    email: d.walter@mpdl.mpg.de
    affiliation:
      - name: Max Planck Digital Library
        city: Munich
        url: https://www.mpdl.mpg.de/en/ 
---

This material was created for the LMU & MPG Open Science Summer School 2024. During the Summer School the material was accompanied by slides and the tasks were done in groups. Independent of this event, the materials can be used to get an insight into Research Data Management in the context of Open Science and therefore with the goal of a FAIR publication.

This version of the material has been updated by the same group of creators for the MPG Open Science Ambassadors Meeting 2024. All self-paced training elements remain.

## Contributors

This tutorial was authored by Maike Kleemeyer, Larissa Leiminger, Laura Meier, and David Walter (see the author metadata above for affiliations).

## Licenses

The tutorial content is available under the [**CC BY-SA 4.0**](https://creativecommons.org/licenses/by-sa/4.0/) license found at [LICENSE](LICENSE.md). The materials can be used, remixed, adapted, and shared according to the terms of that license.

## Notes

The tutorial was primarily written in 2024 for the LMU & MPG Open Science Summer School, and updated for the MPG Open Science Ambassadors Meeting 2024.

Want to help improve our tutorial website? We welcome contributions from the community! To suggest a change or report an issue, please create a GitHub issue by clicking on the link 'Report an issue' on the respective page, or reach out via [mail](mailto:rdm@ub.uni-muenchen.de).

## Tutorial Template Quarto Extension

This tutorial was written using the [`lmu-osc/tutorial-template`](https://github.com/lmu-osc/tutorial-template) Quarto extension [@callahan2026].

## How to Cite

**To cite this tutorial, please refer to the project's [CITATION.cff](CITATION.cff) file or use the persistent Zenodo DOI for the version you consulted: [10.5281/zenodo.22249817](https://doi.org/10.5281/zenodo.22249817).**
